### ISSUE TITLE
Provide hostname for SNI

### ISSUE THREAD

**Issue by mmastrac** [wintercg/proposal-sockets-api#15]
The hostname negotiation for SNI may be different from the connection address. For example, a client may connect by IP to a service and provide an unresolved hostname on connection. As in #14, this SNI negotation result may need to provided as part of the handshake promise.

**Comment by mmastrac** [comment]
Definitely -- both of those may be required for a successful HTTP/2 or gRPC connection, for example. In terms of TLS options, I'd suggest these are probably the two most important and most common.

**Comment by jasnell** [comment]
Would you be interested in opening a PR adding these? I think we ought to be able to keep it pretty simple, e.g.,

```
const socket = connect('...', { secureTransport: 'on', sni: 'example.org', alpn: ['h1', 'h2'] });
await socket.opened; // see https://github.com/wintercg/proposal-sockets-api/pull/12
console.log(socket.info.sni);  // the negotiated sni. undefined before handshake is complete
console.log(socket.info.alpn); // the negotiated alpn. undefined before handshake is complete
```

**Comment by mmastrac** [comment]
@jasnell Opened a PR for it. Some further comments in #18

**Comment by jasnell** [comment]
This has been added.
