### ISSUE TITLE
Use distinct error names

### ISSUE THREAD

**Issue by Ethan-Arrowood** [wintercg/proposal-sockets-api#3]
I think it would be very useful if we added distinct errors to the spec, sorta along the lines of https://webidl.spec.whatwg.org/#idl-DOMException-error-names . Similarly, Fetch's [network error](https://fetch.spec.whatwg.org/#concept-network-error) is a good example of something we could adopt. I find consistent errors between platforms a huge miss currently. Would be awesome if we could improve that this time around.

**Comment by dom96** [comment]
Sure, let's do it

**Comment by Ethan-Arrowood** [comment]
I will make a PR updating the spec 👍
