### ISSUE TITLE
Use `URL` for SocketAddress

### ISSUE THREAD

**Issue by Ethan-Arrowood** [wintercg/proposal-sockets-api#7]
Should the `connect` method work with a `URL` instance as the first parameter? 

`URL` is a web api just like `Steams` so i think its sufficient to include it

**Comment by dom96** [comment]
A `URL` object should already fit the `SocketAddress` dictionary defined in the spec (`URL` has `port` and `hostname` fields). Not sure we need to be explicit about allowing `URL`.

**Comment by Ethan-Arrowood** [comment]
Yeah thats right. I didn't realize that at first, but totally makes sense. No reason to specifically constrain it
